// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YogaInstructor.Api.Data;

#nullable disable

namespace YogaInstructor.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260407073901_FinalDataCleanUp")]
    partial class FinalDataCleanUp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("YogaInstructor.Api.Models.YogaClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Intensity")
                        .HasColumnType("int");

                    b.Property<bool>("IsDoctorRecommended")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ScientificBenefits")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("YogaClasses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2006, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            Difficulty = "Beginner",
                            Intensity = 3,
                            IsDoctorRecommended = true,
                            Price = 499.99m,
                            ScientificBenefits = "Reduce Cortisol and Improves Spinal Mobility",
                            Title = ""
                        });
                });

            modelBuilder.Entity("YogaInstructor.Api.Models.YogaClassTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YogaClassId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("YogaClassId");

                    b.ToTable("YogaClassTranslations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A gental start to your day.",
                            LanguageCode = "en",
                            Title = "Morning Flow",
                            YogaClassId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "आपके दिन की एक कोमल शुरुआत।",
                            LanguageCode = "hi",
                            Title = "सुबह का प्रवाह",
                            YogaClassId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "તમારા દિવસની નમ્ર શરૂઆત.",
                            LanguageCode = "gu",
                            Title = "સવારનો પ્રવાહ",
                            YogaClassId = 1
                        });
                });

            modelBuilder.Entity("YogaInstructor.Api.Models.YogaClassTranslation", b =>
                {
                    b.HasOne("YogaInstructor.Api.Models.YogaClass", "YogaClass")
                        .WithMany("YogaClassTranslations")
                        .HasForeignKey("YogaClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("YogaClass");
                });

            modelBuilder.Entity("YogaInstructor.Api.Models.YogaClass", b =>
                {
                    b.Navigation("YogaClassTranslations");
                });
#pragma warning restore 612, 618
        }
    }
}
